IyBMaWNlbnNlZCB0byB0aGUgQXBhY2hlIFNvZnR3YXJlIEZvdW5kYXRpb24g
KEFTRikgdW5kZXIgb25lCiMgb3IgbW9yZSBjb250cmlidXRvciBsaWNlbnNl
IGFncmVlbWVudHMuICBTZWUgdGhlIE5PVElDRSBmaWxlCiMgZGlzdHJpYnV0
ZWQgd2l0aCB0aGlzIHdvcmsgZm9yIGFkZGl0aW9uYWwgaW5mb3JtYXRpb24K
IyByZWdhcmRpbmcgY29weXJpZ2h0IG93bmVyc2hpcC4gIFRoZSBBU0YgbGlj
ZW5zZXMgdGhpcyBmaWxlCiMgdG8geW91IHVuZGVyIHRoZSBBcGFjaGUgTGlj
ZW5zZSwgVmVyc2lvbiAyLjAgKHRoZQojICJMaWNlbnNlIik7IHlvdSBtYXkg
bm90IHVzZSB0aGlzIGZpbGUgZXhjZXB0IGluIGNvbXBsaWFuY2UKIyB3aXRo
IHRoZSBMaWNlbnNlLiAgWW91IG1heSBvYnRhaW4gYSBjb3B5IG9mIHRoZSBM
aWNlbnNlIGF0CiMKIyAgIGh0dHA6Ly93d3cuYXBhY2hlLm9yZy9saWNlbnNl
cy9MSUNFTlNFLTIuMAojCiMgVW5sZXNzIHJlcXVpcmVkIGJ5IGFwcGxpY2Fi
bGUgbGF3IG9yIGFncmVlZCB0byBpbiB3cml0aW5nLAojIHNvZnR3YXJlIGRp
c3RyaWJ1dGVkIHVuZGVyIHRoZSBMaWNlbnNlIGlzIGRpc3RyaWJ1dGVkIG9u
IGFuCiMgIkFTIElTIiBCQVNJUywgV0lUSE9VVCBXQVJSQU5USUVTIE9SIENP
TkRJVElPTlMgT0YgQU5ZCiMgS0lORCwgZWl0aGVyIGV4cHJlc3Mgb3IgaW1w
bGllZC4gIFNlZSB0aGUgTGljZW5zZSBmb3IgdGhlCiMgc3BlY2lmaWMgbGFu
Z3VhZ2UgZ292ZXJuaW5nIHBlcm1pc3Npb25zIGFuZCBsaW1pdGF0aW9ucwoj
IHVuZGVyIHRoZSBMaWNlbnNlLgoKIyBodHRwczovL2N3aWtpLmFwYWNoZS5v
cmcvY29uZmx1ZW5jZS9kaXNwbGF5L0lORlJBL2dpdCstKy5hc2YueWFtbCtm
ZWF0dXJlcwotLS0KZ2l0aHViOgogIGRlc2NyaXB0aW9uOiAiQXBhY2hlIEFp
cmZsb3cgLSBBIHBsYXRmb3JtIHRvIHByb2dyYW1tYXRpY2FsbHkgYXV0aG9y
LCBzY2hlZHVsZSwgYW5kIG1vbml0b3Igd29ya2Zsb3dzIgogIGhvbWVwYWdl
OiBodHRwczovL2FpcmZsb3cuYXBhY2hlLm9yZy8KICBsYWJlbHM6CiAgICAt
IGFpcmZsb3cKICAgIC0gYXBhY2hlCiAgICAtIGFwYWNoZS1haXJmbG93CiAg
ICAtIHB5dGhvbgogICAgLSBzY2hlZHVsZXIKICAgIC0gd29ya2Zsb3cKICBm
ZWF0dXJlczoKICAgICMgRW5hYmxlIGlzc3VlcyBtYW5hZ2VtZW50CiAgICBp
c3N1ZXM6IHRydWUKICAgICMgRW5hYmxlIHByb2plY3RzIGZvciBwcm9qZWN0
IG1hbmFnZW1lbnQgYm9hcmRzCiAgICBwcm9qZWN0czogdHJ1ZQogICAgIyBF
bmFibGUgd2lraSBmb3IgZG9jdW1lbnRhdGlvbgogICAgd2lraTogZmFsc2UK
CiAgZW5hYmxlZF9tZXJnZV9idXR0b25zOgogICAgc3F1YXNoOiB0cnVlCiAg
ICBtZXJnZTogZmFsc2UKICAgIHJlYmFzZTogZmFsc2UKCiAgcHJvdGVjdGVk
X2JyYW5jaGVzOgogICAgbWFzdGVyOgogICAgICByZXF1aXJlZF9wdWxsX3Jl
cXVlc3RfcmV2aWV3czoKICAgICAgICByZXF1aXJlZF9hcHByb3ZpbmdfcmV2
aWV3X2NvdW50OiAxCiAgICB2MS0xMC1zdGFibGU6CiAgICAgIHJlcXVpcmVk
X3B1bGxfcmVxdWVzdF9yZXZpZXdzOgogICAgICAgIHJlcXVpcmVkX2FwcHJv
dmluZ19yZXZpZXdfY291bnQ6IDEK
